### ISSUE TITLE
Send timing information with order

### ISSUE THREAD

**Issue by JeroenBoersma** [linktracker/magento-module#4]
On sending the order a timing tag `t=20201005.023000` should be added.

* parameter `t`
* value `YYYYMMDD.HHIISS`
* timezone UTC

**Comment by linktracker** [comment]
Preferred timezone: UTC + 2

**Comment by JeroenBoersma** [comment]
Ok, so we need to add a definition for this somewhere...

**Comment by JeroenBoersma** [comment]
Released [2.0.0](https://github.com/linktracker/magento-module/releases/tag/2.0.0)

update the clients to reflect the change
